server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
#  security:
#    user:
#      name: username
#      password: password